Force push latest release tracking branch
Added in https://github.com/alphagov/govuk_elements/pull/232

The push failed in the most recent release/build:

```
To git@github.com:alphagov/govuk_elements.git
 ! [rejected]        master -> latest-release (non-fast-forward)
error: failed to push some refs to 'git@github.com:alphagov/govuk_elements.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
```

Given it's just for tracking, we can safely force push.